### ISSUE TITLE
beefproj 실행 불가

### ISSUE THREAD

**Issue by jellygit** [beefproj/beefproj.github.io#1]
x86 CPU 에서 실행했더니 에러나면서 실행 불가합니다.

1. docker-compose.yml 다운로드
2. sudo docker-compose up -d 
3. mongodb, mariadb 정상 실행, beef 는 계속해서 재실행 시도
 
beef 가 go로 작성된 것으로 보이는데 아래와 같이 실행이 안됩니다.
```
~/work/beef   sudo docker ps -a 
CONTAINER ID   IMAGE                                                       COMMAND                  CREATED          STATUS                       PORTS                                       NAMES
004e15575ffe   beefproj/beefproj:latest                                    "/app/beef"              24 minutes ago   Exited (1) 21 minutes ago                                                beefproj

sudo docker logs 004e15575ffe                                                                                                                                                
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
...(반복)...
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error

[root@Arch docker]# cd overlay2/3fdc083edcb11746f36ae3673821e02d0e409865c86149fc1559ff8188a82f4a/diff/app/
[root@Arch app]# ls -l
.rwxr-xr-x root root 14 MB Thu Dec 30 21:40:01 2021  beef
[root@Arch app]# ./beef
-bash: ./beef: cannot execute binary file: Exec format error
```

go에 대해 잘 모르겠습니다만 https://www.inflearn.com/questions/38078 와 같이 소스코드 넣고 빌드할 수 있도록 해야 하지 않을까요?

----
추가: 라즈베리파이에서 실행한다는 점을 간과했습니다.
https://stackoverflow.com/questions/55786898/standard-init-linux-go190-exec-user-process-caused-exec-format-error-when-ru

`RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o [OUTPUT] .`

**Comment by jellygit** [comment]
ARM 기반 M1 맥북에선 실행 잘 됩니다.

---
Macbook Apple M1 칩셋에서도 일부 실행 되다 코어 덤프가 뜹니다.

1. docker-compose up -d 
2. '소고기 프로젝트 셋업 (2/2)' 에 관련 정보 입력
3. 로그인 시도 -> 연결초기화

```
docker logs beefproj 컨테이너 확인
sudo docker logs 0741773a74fa
Password:
2022/01/01 16:43:55 MongoDB: root@bf-mongo:27017/sogogi
2022/01/01 16:44:05 AppConfig not found in MongoDB, entering setup mode...
2022/01/01 16:44:05 Basic Setup mode started on port 80 ...
2022/01/02 13:23:06 MongoDB: root@bf-mongo:27017/sogogi
2022/01/02 13:23:13 AppConfig not found in MongoDB, entering setup mode...
2022/01/02 13:23:13 Basic Setup mode started on port 80 ...
2022/01/02 15:56:00 MySQL: sogogi@bf-mysql:3306/sogogi
[createAdmin] NewAdmin(beefwebpo,최고관리자) created
[createAdmin] NewAdmin(ebestpo,프록시앱) created
[system] Table 'chart_foreign' created.
[system] Table 'chart_ohlcv' created.
[system] Table 'chart_stock' created.
[system] Table 'dic_fsymbol' created.
[system] Table 'dic_shcode' created.
[system] MySQL schema updated.
[system] Lookup data prefilled.
2022/01/02 15:56:02 Setup mode ended.
2022/01/02 15:56:02 Telegram BotToken empty, Telegram will not be available.
Operation not permitted (src/thread.cpp:232)
qemu: uncaught target signal 6 (Aborted) - core dumped
``` 

arm, arm64 아키텍쳐 차이 때문일까요? 이미지 빌드 할 때 buildx 사용해서 타 아키텍쳐도 지원 됐으면 좋겠습니다.

**Comment by beefproj** [comment]
죄송합니다만 제가 맥북이 없어서 테스트해 볼 수 없는 내용이라 해결이 어렵겠네요.
다른 아키텍처 지원은 개발 및 테스트 부담, 이슈의 복잡도가 증가할 것 같아서 고려하고 있지 않습니다.
라즈베리파이4 나오면서 라즈베리파이2,3은 떠리로 처분하는 분들이 많은데 중고로 구입해보셔도 큰 부담은 아닐것 같습니다.
(사실 요새 물류 문제로 라즈베리파이4 품절이라 신품 구매가 안됩니다, 저도 없어요 ㅠ)

**Comment by jellygit** [comment]
라즈베리파이4b에 64bit 리눅스(라즈비안64bit) 설치 시에 실행 가능하네요.

소고기 프로젝트에 필요한 이미지들의 아키텍쳐를 확인해보니 mongo, mariadb 는 arm64 v8 / beefproj 는 arm v7 (32bit) 네요.
라즈베리파이4B에 라즈비안32bit 설치했더니 mongo db 부터 설치가 안되길래 확인해보았습니다.
64bit 라즈비안에서 32bit 하위 호완이 되어 실행 잘 되었습니다.

REPOSITORY          TAG       IMAGE ID       CREATED       SIZE
mongo               4.4       fe68158e8cbf   3 days ago    414MB
        "Architecture": "arm64",
        "Variant": "v8",
        "Os": "linux",
mariadb             latest    7185139442f4   3 days ago    394MB
        "Architecture": "arm64",
        "Variant": "v8",
        "Os": "linux"
beefproj/beefproj   latest    5beb34f03650   5 weeks ago   145MB
        "Architecture": "arm",
        "Variant": "v7", 
        "Os": "linux",
